version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: transom-mongoose-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: test
    volumes:
      - mongodb_data:/data/db
    networks:
      - transom-network

volumes:
  mongodb_data:

networks:
  transom-network:
    driver: bridge